### ISSUE TITLE
작성페이지, 수정페이지, 상세페이지 버그

### ISSUE THREAD

**Issue by suzz-in** [zzw-final/zzw-FE#70]
## Issue: ✅ FEATURE
작성페이지, 수정페이지, 상세페이지

## Description
버그 수정 해결

## Todo
- [x] 작성페이지 태그 1~10개 제한
- [x] 작성페이지 이미지 엑박
- [x] 상세페이지 태그 좌우스크롤
